graphprotocol/networks-registry

- package.json
- registry/eip155/arbitrum-one.json
- registry/eip155/base.json
- registry/eip155/celo-alfajores.json
- registry/eip155/xai.json
> Alfajores, base, arb-one, xai updates

- package.json
- registry/eip155/lens-sepolia.json
- src/generate_table.ts
> add lens testnet

- package.json
- registry/eip155/bsc.json
- registry/eip155/iotex.json
- registry/eip155/mainnet.json
- registry/eip155/matic.json
- registry/eip155/polygon-zkevm-cardona.json
> Update etherscan api urls

- package.json
- registry/eip155/hemi-sepolia.json
Added new chain: Hemi Sepolia
`Bun validate` returned no errors
Incremented package version to 0.6.15
> added hemi-sepolia

- package.json
- registry/eip155/joc.json
Added japan open chain (mainnet)
`bun validate` successful
> added japan open chain

- package.json
- registry/eip155/hemi.json
`Bun validate` successful
Completed these checks:
- [v] Use a meaningful title for the pull request
- [v] Increment `package.json` version
- [v] Pass validation checks
> Added explorer, api and rpc URLs for Hemi (mainnet)

- package.json
- registry/eip155/soneium-testnet.json
- registry/eip155/soneium.json
Added new chain `soneium`. 
- [v] Increment `package.json` version
- [v] Pass validation checks
> Added soneium mainnet

- package.json
- registry/eip155/mint.json
> add mint chain

- package.json
- registry/eip155/monad-testnet.json
This is dummy data for just to show up on the cli and actual URLs will be added after 22nd Jan
> add monad testnet with dummy data

- package.json
- registry/eip155/mode-mainnet.json
- registry/eip155/moonbeam.json
- registry/eip155/zora.json
> set true flag for zora mode moonbeam

- .github/workflows/publish.yml
- package.json
> temporarily disable validation

- .github/workflows/publish.yml
- src/validate.ts
> disable graph networks validation

- package.json
- registry/eip155/berachain-bartio.json
- registry/eip155/fraxtal.json
- registry/eip155/mint-sepolia.json
- registry/eip155/vana-moksha.json
- registry/eip155/vana.json
- registry/eip155/viction.json
Added chains: viction, mint-sepolia, berachain-bartio, fraxtal, vana, vana-moksha
> Added chains: viction, mint-sepolia, berachain-bartio, fraxtal, vana, vana-moksha

- package.json
- registry/eip155/abstract.json
Added RPC, API and explorer URLs for `abstract`
> Added rpc and explorer urls for abstract

- package.json
- registry/eip155/lens-testnet.json
- registry/eip155/vana.json
- registry/eip155/zetachain.json
Added ZetaChain
Added icon for vana
Updated services for lens-testnet
> added zetachain, updated vana & lens-testnet

- package.json
- registry/eip155/berachain-bartio.json
- registry/eip155/mint-sepolia.json
> Cleanup names

- registry/eip155/polygon-zkevm-cardona.json
- registry/eip155/polygon-zkevm.json
- src/maintenance.ts
- src/validate_firehose.ts
- src/validate_logic.ts
- src/validate_urls.ts
Various improvements to maintenance action
> chore: Improve maintenance action

- package.json
- registry/eip155/ink-sepolia.json
- registry/eip155/ink.json
- registry/eip155/joc-testnet.json
- registry/eip155/joc.json
> add ink, ink sepolia and joc testnet

- package.json
- registry/eip155/joc-testnet.json
- registry/solana/solana-accounts.json
- src/validate_logic.ts
Solana Accounts is a special view into Solana Mainnet
> Add solana accounts chain

- package.json
- registry/eip155/berachain.json
Berachain rpc, explorer, api urls added
> berachain urls added

- package.json
- registry/eip155/unichain-testnet.json
- registry/eip155/unichain.json
> Add unichain

- package.json
- registry/eip155/apechain.json
- registry/eip155/autonomys-taurus.json
- registry/eip155/swellchain-sepolia.json
- registry/eip155/swellchain.json
- autonomys-taurus, 
- swellchain, 
- swellchain-sepolia,
- apechain
> Added chains autonomys, swellchain, apechain

- package.json
- registry/eip155/apechain.json
- registry/eip155/berachain.json
- registry/eip155/chiliz-testnet.json
- registry/eip155/linea-sepolia.json
- registry/eip155/soneium.json
- registry/eip155/xlayer-sepolia.json
- registry/starknet/starknet-mainnet.json
- registry/starknet/starknet-testnet.json
- src/validate_firehose.ts
- src/validate_logic.ts
- add missing firehose endpoints
- remove outdated ones
- improve firehose validation logic and error messages
> Add new firehoses

- package.json
- registry/bip122/btc.json
- registry/eip155/arbitrum-one.json
- registry/eip155/bnb-op.json
- registry/eip155/boba-bnb.json
- registry/eip155/clover.json
- registry/eip155/fraxtal.json
- registry/eip155/mint.json
- registry/eip155/moonbeam.json
- registry/eip155/moonriver.json
- registry/eip155/optimism.json
- registry/eip155/polygon-zkevm.json
- registry/eip155/zksync-era.json
- registry/solana/solana-mainnet-beta.json
- src/validate_logic.ts
> Add missing mainnet aliases

- package.json
- registry/eip155/metis.json
added metis
(Metis Andromeda Mainnet)
> added metis

- package.json
- registry/starknet/starknet-testnet.json
Added services for starknet-testnet to be supported by Studio
> added studio & SPS services for starknet-testnet

- package.json
- registry/eip155/zilliqa-protomainnet.json
> added zilliqa protomainnet

- package.json
- registry/eip155/peaq.json
Added Peaq Network
Etherscan compatible API url not available in the near future
> Added Peaq

- package.json
- registry/eip155/arbitrum-sepolia.json
- registry/eip155/polygon-zkevm.json
- registry/eip155/rootstock.json
- registry/eip155/zksync-era.json
Starting today 4 new chains with indexing rewards
Fixes #95
> Add new chains with indexing rewards

- package.json
- registry/eip155/hoodi.json
> added hoodi

- package.json
- registry/eip155/arbitrum-one.json
- registry/eip155/arbitrum-sepolia.json
> fix: arb-sepolia alias does not belong in Arbitrum One

- package.json
- registry/eip155/manta.json
- registry/eip155/megaeth-testnet.json
- src/validate_logic.ts
> Added MegaETH testnet

- package.json
- registry/eip155/lens-testnet.json
- registry/eip155/lens.json
> Add Lens Mainnet

- package.json
- registry/eip155/base-sepolia.json
- registry/eip155/berachain.json
- registry/eip155/chiliz-testnet.json
- registry/eip155/gnosis.json
- registry/eip155/holesky.json
- registry/eip155/hoodi.json
- registry/eip155/linea-sepolia.json
- registry/eip155/mainnet.json
- registry/eip155/optimism-sepolia.json
- registry/eip155/sepolia.json
- registry/eip155/soneium.json
- registry/eip155/sonic.json
- registry/eip155/unichain.json
- registry/eip155/xlayer-sepolia.json
- registry/eip155/zksync-era.json
- registry/stellar/stellar.json
- src/validate_firehose.ts
- added indexing rewards for 3 chains
- addressed errors and warnings
- removed dead endpoints
- added new endpoints
> Registry maintenance

- package.json
- registry/eip155/ronin.json
Ronin ready for Studio. 
No etherscan compatible APIs available yet.
> Added Studio Service for Ronin

- package.json
- registry/eip155/katana-tatara.json
> added katana tatara testnet

- package.json
- registry/eip155/katana-tatara.json
- registry/eip155/katana.json
- registry/eip155/ozean-poseidon.json
- registry/eip155/status-sepolia.json
Added `status-sepolia`.
Added icons for katana & ozean
> added status sepolia, updated icons

- .github/workflows/auto-version-bump.yml
- README.md
- package.json
- pull_request_template.md
- registry/antelope/eos.json
- registry/beacon/hoodi-cl.json
Let's see if auto-bump works @GabrielCartier
> add hoodi-cl chain

- package.json
- registry/eip155/cronos.json
Subgraph Studio support enabled for Cronos
> enabled subgraphs for cronos

- package.json
- registry/eip155/injective-evm-testnet.json
- registry/eip155/sei-mainnet.json
- src/validate_logic.ts
fixed injective-evm-testnet and sei-mainnet registry
> Fix Injective-EVM + Sei-Mainnet 

- package.json
- registry/eip155/fantom.json
- registry/eip155/gravity-testnet.json
- registry/eip155/matic.json
- registry/eip155/moonriver.json
- registry/eip155/scroll.json
- registry/eip155/tron-evm.json
- registry/eip155/xlayer-sepolia.json
- registry/tron/tron.json
Addressed some maintenance issues
> Cleanup RPC endpoints
